// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dict.proto

package ru.mugattarov.proto;

public final class DictOuterClass {
  private DictOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DictOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru_mugattarov_proto.Dict)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    java.util.List<ru.mugattarov.proto.DictOuterClass.Noun> 
        getNounsList();
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    ru.mugattarov.proto.DictOuterClass.Noun getNouns(int index);
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    int getNounsCount();
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    java.util.List<? extends ru.mugattarov.proto.DictOuterClass.NounOrBuilder> 
        getNounsOrBuilderList();
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    ru.mugattarov.proto.DictOuterClass.NounOrBuilder getNounsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ru_mugattarov_proto.Dict}
   */
  public  static final class Dict extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru_mugattarov_proto.Dict)
      DictOrBuilder {
    // Use Dict.newBuilder() to construct.
    private Dict(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dict() {
      nouns_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Dict(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                nouns_ = new java.util.ArrayList<ru.mugattarov.proto.DictOuterClass.Noun>();
                mutable_bitField0_ |= 0x00000001;
              }
              nouns_.add(
                  input.readMessage(ru.mugattarov.proto.DictOuterClass.Noun.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          nouns_ = java.util.Collections.unmodifiableList(nouns_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Dict_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Dict_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.mugattarov.proto.DictOuterClass.Dict.class, ru.mugattarov.proto.DictOuterClass.Dict.Builder.class);
    }

    public static final int NOUNS_FIELD_NUMBER = 1;
    private java.util.List<ru.mugattarov.proto.DictOuterClass.Noun> nouns_;
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    public java.util.List<ru.mugattarov.proto.DictOuterClass.Noun> getNounsList() {
      return nouns_;
    }
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    public java.util.List<? extends ru.mugattarov.proto.DictOuterClass.NounOrBuilder> 
        getNounsOrBuilderList() {
      return nouns_;
    }
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    public int getNounsCount() {
      return nouns_.size();
    }
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    public ru.mugattarov.proto.DictOuterClass.Noun getNouns(int index) {
      return nouns_.get(index);
    }
    /**
     * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
     */
    public ru.mugattarov.proto.DictOuterClass.NounOrBuilder getNounsOrBuilder(
        int index) {
      return nouns_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < nouns_.size(); i++) {
        output.writeMessage(1, nouns_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < nouns_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nouns_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.mugattarov.proto.DictOuterClass.Dict)) {
        return super.equals(obj);
      }
      ru.mugattarov.proto.DictOuterClass.Dict other = (ru.mugattarov.proto.DictOuterClass.Dict) obj;

      boolean result = true;
      result = result && getNounsList()
          .equals(other.getNounsList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getNounsCount() > 0) {
        hash = (37 * hash) + NOUNS_FIELD_NUMBER;
        hash = (53 * hash) + getNounsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mugattarov.proto.DictOuterClass.Dict parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.mugattarov.proto.DictOuterClass.Dict prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru_mugattarov_proto.Dict}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru_mugattarov_proto.Dict)
        ru.mugattarov.proto.DictOuterClass.DictOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Dict_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Dict_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.mugattarov.proto.DictOuterClass.Dict.class, ru.mugattarov.proto.DictOuterClass.Dict.Builder.class);
      }

      // Construct using ru.mugattarov.proto.DictOuterClass.Dict.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNounsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (nounsBuilder_ == null) {
          nouns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nounsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Dict_descriptor;
      }

      public ru.mugattarov.proto.DictOuterClass.Dict getDefaultInstanceForType() {
        return ru.mugattarov.proto.DictOuterClass.Dict.getDefaultInstance();
      }

      public ru.mugattarov.proto.DictOuterClass.Dict build() {
        ru.mugattarov.proto.DictOuterClass.Dict result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.mugattarov.proto.DictOuterClass.Dict buildPartial() {
        ru.mugattarov.proto.DictOuterClass.Dict result = new ru.mugattarov.proto.DictOuterClass.Dict(this);
        int from_bitField0_ = bitField0_;
        if (nounsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nouns_ = java.util.Collections.unmodifiableList(nouns_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nouns_ = nouns_;
        } else {
          result.nouns_ = nounsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.mugattarov.proto.DictOuterClass.Dict) {
          return mergeFrom((ru.mugattarov.proto.DictOuterClass.Dict)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.mugattarov.proto.DictOuterClass.Dict other) {
        if (other == ru.mugattarov.proto.DictOuterClass.Dict.getDefaultInstance()) return this;
        if (nounsBuilder_ == null) {
          if (!other.nouns_.isEmpty()) {
            if (nouns_.isEmpty()) {
              nouns_ = other.nouns_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNounsIsMutable();
              nouns_.addAll(other.nouns_);
            }
            onChanged();
          }
        } else {
          if (!other.nouns_.isEmpty()) {
            if (nounsBuilder_.isEmpty()) {
              nounsBuilder_.dispose();
              nounsBuilder_ = null;
              nouns_ = other.nouns_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nounsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNounsFieldBuilder() : null;
            } else {
              nounsBuilder_.addAllMessages(other.nouns_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.mugattarov.proto.DictOuterClass.Dict parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.mugattarov.proto.DictOuterClass.Dict) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ru.mugattarov.proto.DictOuterClass.Noun> nouns_ =
        java.util.Collections.emptyList();
      private void ensureNounsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nouns_ = new java.util.ArrayList<ru.mugattarov.proto.DictOuterClass.Noun>(nouns_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.mugattarov.proto.DictOuterClass.Noun, ru.mugattarov.proto.DictOuterClass.Noun.Builder, ru.mugattarov.proto.DictOuterClass.NounOrBuilder> nounsBuilder_;

      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public java.util.List<ru.mugattarov.proto.DictOuterClass.Noun> getNounsList() {
        if (nounsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nouns_);
        } else {
          return nounsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public int getNounsCount() {
        if (nounsBuilder_ == null) {
          return nouns_.size();
        } else {
          return nounsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public ru.mugattarov.proto.DictOuterClass.Noun getNouns(int index) {
        if (nounsBuilder_ == null) {
          return nouns_.get(index);
        } else {
          return nounsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder setNouns(
          int index, ru.mugattarov.proto.DictOuterClass.Noun value) {
        if (nounsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNounsIsMutable();
          nouns_.set(index, value);
          onChanged();
        } else {
          nounsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder setNouns(
          int index, ru.mugattarov.proto.DictOuterClass.Noun.Builder builderForValue) {
        if (nounsBuilder_ == null) {
          ensureNounsIsMutable();
          nouns_.set(index, builderForValue.build());
          onChanged();
        } else {
          nounsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder addNouns(ru.mugattarov.proto.DictOuterClass.Noun value) {
        if (nounsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNounsIsMutable();
          nouns_.add(value);
          onChanged();
        } else {
          nounsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder addNouns(
          int index, ru.mugattarov.proto.DictOuterClass.Noun value) {
        if (nounsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNounsIsMutable();
          nouns_.add(index, value);
          onChanged();
        } else {
          nounsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder addNouns(
          ru.mugattarov.proto.DictOuterClass.Noun.Builder builderForValue) {
        if (nounsBuilder_ == null) {
          ensureNounsIsMutable();
          nouns_.add(builderForValue.build());
          onChanged();
        } else {
          nounsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder addNouns(
          int index, ru.mugattarov.proto.DictOuterClass.Noun.Builder builderForValue) {
        if (nounsBuilder_ == null) {
          ensureNounsIsMutable();
          nouns_.add(index, builderForValue.build());
          onChanged();
        } else {
          nounsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder addAllNouns(
          java.lang.Iterable<? extends ru.mugattarov.proto.DictOuterClass.Noun> values) {
        if (nounsBuilder_ == null) {
          ensureNounsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nouns_);
          onChanged();
        } else {
          nounsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder clearNouns() {
        if (nounsBuilder_ == null) {
          nouns_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nounsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public Builder removeNouns(int index) {
        if (nounsBuilder_ == null) {
          ensureNounsIsMutable();
          nouns_.remove(index);
          onChanged();
        } else {
          nounsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public ru.mugattarov.proto.DictOuterClass.Noun.Builder getNounsBuilder(
          int index) {
        return getNounsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public ru.mugattarov.proto.DictOuterClass.NounOrBuilder getNounsOrBuilder(
          int index) {
        if (nounsBuilder_ == null) {
          return nouns_.get(index);  } else {
          return nounsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public java.util.List<? extends ru.mugattarov.proto.DictOuterClass.NounOrBuilder> 
           getNounsOrBuilderList() {
        if (nounsBuilder_ != null) {
          return nounsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nouns_);
        }
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public ru.mugattarov.proto.DictOuterClass.Noun.Builder addNounsBuilder() {
        return getNounsFieldBuilder().addBuilder(
            ru.mugattarov.proto.DictOuterClass.Noun.getDefaultInstance());
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public ru.mugattarov.proto.DictOuterClass.Noun.Builder addNounsBuilder(
          int index) {
        return getNounsFieldBuilder().addBuilder(
            index, ru.mugattarov.proto.DictOuterClass.Noun.getDefaultInstance());
      }
      /**
       * <code>repeated .ru_mugattarov_proto.Noun nouns = 1;</code>
       */
      public java.util.List<ru.mugattarov.proto.DictOuterClass.Noun.Builder> 
           getNounsBuilderList() {
        return getNounsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ru.mugattarov.proto.DictOuterClass.Noun, ru.mugattarov.proto.DictOuterClass.Noun.Builder, ru.mugattarov.proto.DictOuterClass.NounOrBuilder> 
          getNounsFieldBuilder() {
        if (nounsBuilder_ == null) {
          nounsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ru.mugattarov.proto.DictOuterClass.Noun, ru.mugattarov.proto.DictOuterClass.Noun.Builder, ru.mugattarov.proto.DictOuterClass.NounOrBuilder>(
                  nouns_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nouns_ = null;
        }
        return nounsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ru_mugattarov_proto.Dict)
    }

    // @@protoc_insertion_point(class_scope:ru_mugattarov_proto.Dict)
    private static final ru.mugattarov.proto.DictOuterClass.Dict DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.mugattarov.proto.DictOuterClass.Dict();
    }

    public static ru.mugattarov.proto.DictOuterClass.Dict getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dict>
        PARSER = new com.google.protobuf.AbstractParser<Dict>() {
      public Dict parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Dict(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dict> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dict> getParserForType() {
      return PARSER;
    }

    public ru.mugattarov.proto.DictOuterClass.Dict getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface NounOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ru_mugattarov_proto.Noun)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string noun = 1;</code>
     */
    java.lang.String getNoun();
    /**
     * <code>optional string noun = 1;</code>
     */
    com.google.protobuf.ByteString
        getNounBytes();

    /**
     * <code>optional string def = 2;</code>
     */
    java.lang.String getDef();
    /**
     * <code>optional string def = 2;</code>
     */
    com.google.protobuf.ByteString
        getDefBytes();
  }
  /**
   * Protobuf type {@code ru_mugattarov_proto.Noun}
   */
  public  static final class Noun extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ru_mugattarov_proto.Noun)
      NounOrBuilder {
    // Use Noun.newBuilder() to construct.
    private Noun(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Noun() {
      noun_ = "";
      def_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Noun(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              noun_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              def_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Noun_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Noun_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.mugattarov.proto.DictOuterClass.Noun.class, ru.mugattarov.proto.DictOuterClass.Noun.Builder.class);
    }

    public static final int NOUN_FIELD_NUMBER = 1;
    private volatile java.lang.Object noun_;
    /**
     * <code>optional string noun = 1;</code>
     */
    public java.lang.String getNoun() {
      java.lang.Object ref = noun_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        noun_ = s;
        return s;
      }
    }
    /**
     * <code>optional string noun = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNounBytes() {
      java.lang.Object ref = noun_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        noun_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEF_FIELD_NUMBER = 2;
    private volatile java.lang.Object def_;
    /**
     * <code>optional string def = 2;</code>
     */
    public java.lang.String getDef() {
      java.lang.Object ref = def_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        def_ = s;
        return s;
      }
    }
    /**
     * <code>optional string def = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDefBytes() {
      java.lang.Object ref = def_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        def_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNounBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, noun_);
      }
      if (!getDefBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, def_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNounBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, noun_);
      }
      if (!getDefBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, def_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ru.mugattarov.proto.DictOuterClass.Noun)) {
        return super.equals(obj);
      }
      ru.mugattarov.proto.DictOuterClass.Noun other = (ru.mugattarov.proto.DictOuterClass.Noun) obj;

      boolean result = true;
      result = result && getNoun()
          .equals(other.getNoun());
      result = result && getDef()
          .equals(other.getDef());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NOUN_FIELD_NUMBER;
      hash = (53 * hash) + getNoun().hashCode();
      hash = (37 * hash) + DEF_FIELD_NUMBER;
      hash = (53 * hash) + getDef().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ru.mugattarov.proto.DictOuterClass.Noun parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ru.mugattarov.proto.DictOuterClass.Noun prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ru_mugattarov_proto.Noun}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ru_mugattarov_proto.Noun)
        ru.mugattarov.proto.DictOuterClass.NounOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Noun_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Noun_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ru.mugattarov.proto.DictOuterClass.Noun.class, ru.mugattarov.proto.DictOuterClass.Noun.Builder.class);
      }

      // Construct using ru.mugattarov.proto.DictOuterClass.Noun.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        noun_ = "";

        def_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ru.mugattarov.proto.DictOuterClass.internal_static_ru_mugattarov_proto_Noun_descriptor;
      }

      public ru.mugattarov.proto.DictOuterClass.Noun getDefaultInstanceForType() {
        return ru.mugattarov.proto.DictOuterClass.Noun.getDefaultInstance();
      }

      public ru.mugattarov.proto.DictOuterClass.Noun build() {
        ru.mugattarov.proto.DictOuterClass.Noun result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ru.mugattarov.proto.DictOuterClass.Noun buildPartial() {
        ru.mugattarov.proto.DictOuterClass.Noun result = new ru.mugattarov.proto.DictOuterClass.Noun(this);
        result.noun_ = noun_;
        result.def_ = def_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ru.mugattarov.proto.DictOuterClass.Noun) {
          return mergeFrom((ru.mugattarov.proto.DictOuterClass.Noun)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ru.mugattarov.proto.DictOuterClass.Noun other) {
        if (other == ru.mugattarov.proto.DictOuterClass.Noun.getDefaultInstance()) return this;
        if (!other.getNoun().isEmpty()) {
          noun_ = other.noun_;
          onChanged();
        }
        if (!other.getDef().isEmpty()) {
          def_ = other.def_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ru.mugattarov.proto.DictOuterClass.Noun parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ru.mugattarov.proto.DictOuterClass.Noun) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object noun_ = "";
      /**
       * <code>optional string noun = 1;</code>
       */
      public java.lang.String getNoun() {
        java.lang.Object ref = noun_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          noun_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string noun = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNounBytes() {
        java.lang.Object ref = noun_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          noun_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string noun = 1;</code>
       */
      public Builder setNoun(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        noun_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string noun = 1;</code>
       */
      public Builder clearNoun() {
        
        noun_ = getDefaultInstance().getNoun();
        onChanged();
        return this;
      }
      /**
       * <code>optional string noun = 1;</code>
       */
      public Builder setNounBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        noun_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object def_ = "";
      /**
       * <code>optional string def = 2;</code>
       */
      public java.lang.String getDef() {
        java.lang.Object ref = def_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          def_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string def = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDefBytes() {
        java.lang.Object ref = def_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          def_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string def = 2;</code>
       */
      public Builder setDef(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        def_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string def = 2;</code>
       */
      public Builder clearDef() {
        
        def_ = getDefaultInstance().getDef();
        onChanged();
        return this;
      }
      /**
       * <code>optional string def = 2;</code>
       */
      public Builder setDefBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        def_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ru_mugattarov_proto.Noun)
    }

    // @@protoc_insertion_point(class_scope:ru_mugattarov_proto.Noun)
    private static final ru.mugattarov.proto.DictOuterClass.Noun DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ru.mugattarov.proto.DictOuterClass.Noun();
    }

    public static ru.mugattarov.proto.DictOuterClass.Noun getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Noun>
        PARSER = new com.google.protobuf.AbstractParser<Noun>() {
      public Noun parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Noun(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Noun> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Noun> getParserForType() {
      return PARSER;
    }

    public ru.mugattarov.proto.DictOuterClass.Noun getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_mugattarov_proto_Dict_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_mugattarov_proto_Dict_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_mugattarov_proto_Noun_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_mugattarov_proto_Noun_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndict.proto\022\023ru_mugattarov_proto\"0\n\004Dic" +
      "t\022(\n\005nouns\030\001 \003(\0132\031.ru_mugattarov_proto.N" +
      "oun\"!\n\004Noun\022\014\n\004noun\030\001 \001(\t\022\013\n\003def\030\002 \001(\tB\025" +
      "\n\023ru.mugattarov.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ru_mugattarov_proto_Dict_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_mugattarov_proto_Dict_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_mugattarov_proto_Dict_descriptor,
        new java.lang.String[] { "Nouns", });
    internal_static_ru_mugattarov_proto_Noun_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ru_mugattarov_proto_Noun_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_mugattarov_proto_Noun_descriptor,
        new java.lang.String[] { "Noun", "Def", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
